/* ── DEMO DATA ── no database, all hardcoded ── */

const COURSES = [
  {
    id: 'calculus-5',
    title: 'חשבון דיפרנציאלי ואינטגרלי — 5 יח׳',
    subtitle: 'הקורס המקיף ביותר להכנה לבגרות',
    description: 'קורס מקיף הכולל את כל הנושאים הנדרשים לבגרות 5 יחידות — מגבולות ועד אינטגרלים, עם מאות תרגילים מפורטים.',
    category: 'bagrut', categoryLabel: 'בגרות',
    level: 'advanced', levelLabel: 'מתקדם',
    price: 249, originalPrice: 349,
    badge: 'הכי פופולרי',
    icon: '∫', color: '#19b8cc',
    topics: ['גבולות ורציפות', 'נגזרות', 'אינטגרלים', 'פונקציות מרוכבות', 'מבחנים מדומים'],
    includes: { videoHours: '48', exercises: '500+', mockExams: '3', lifetimeAccess: 'כן', supportGroup: 'כן' },
  },
  {
    id: 'calculus-3',
    title: 'חשבון דיפרנציאלי ואינטגרלי — 3 יח׳',
    subtitle: 'הכנה מלאה לבגרות 3 יחידות',
    description: 'קורס מובנה לבגרות 3 יחידות — הסברים ברורים, תרגול ממוקד ואסטרטגיות יעילות לבחינה.',
    category: 'bagrut', categoryLabel: 'בגרות',
    level: 'intermediate', levelLabel: 'בינוני',
    price: 179, originalPrice: 249,
    icon: '∂', color: '#7c3aed',
    topics: ['פונקציות בסיסיות', 'נגזרות ראשונות', 'אינטגרל ראשון', 'שאלות בגרות'],
    includes: { videoHours: '32', exercises: '350+', mockExams: '2', lifetimeAccess: 'כן', supportGroup: '' },
  },
  {
    id: 'algebra',
    title: 'אלגברה — בגרות מלאה',
    subtitle: 'מיסוד מושלם באלגברה',
    description: 'כל הנושאים האלגבריים לבגרות — משוואות, אי-שוויונות, פונקציות וגיאומטריה אנליטית מהיסוד.',
    category: 'bagrut', categoryLabel: 'בגרות',
    level: 'beginner', levelLabel: 'מתחיל',
    price: 149, originalPrice: 199,
    icon: 'α', color: '#059669',
    topics: ['משוואות ואי-שוויונות', 'פונקציות', 'טריגונומטריה', 'גיאומטריה אנליטית'],
    includes: { videoHours: '28', exercises: '400+', mockExams: '1', lifetimeAccess: 'כן', supportGroup: '' },
  },
  {
    id: 'probability',
    title: 'הסתברות וסטטיסטיקה',
    subtitle: 'חומר הסתברות לבגרות',
    description: 'הסתברות קלאסית, משתנים מקריים, התפלגות נורמלית ורגרסיה — הכל בצורה ברורה ומובנית.',
    category: 'bagrut', categoryLabel: 'בגרות',
    level: 'intermediate', levelLabel: 'בינוני',
    price: 129, originalPrice: 179,
    icon: 'P', color: '#d97706',
    topics: ['הסתברות קלאסית', 'משתנים מקריים', 'התפלגות נורמלית', 'רגרסיה לינארית'],
    includes: { videoHours: '20', exercises: '280+', mockExams: '', lifetimeAccess: 'כן', supportGroup: '' },
  },
];

const MARATHONS = [
  /* ── March 2026 (demo) ── */
  {
    id: 'mar-calc5-mar10',
    courseId: 'calculus-5',
    title: 'מרתון חשבון 5 יח׳',
    description: 'יום אינטנסיבי מרוכז: פתרון שאלות בגרות, תרגולים ממוקדים ומבחן מדומה מלא.',
    startDateTime: '2026-03-10T09:00',
    duration: 240, /* minutes */
    category: 'bagrut', categoryLabel: 'בגרות',
    level: 'advanced', levelLabel: 'מתקדם',
    totalSpots: 30, spotsLeft: 7,
    topics: ['נגזרות', 'אינטגרלים', 'גבולות', 'תרגולי מבחן'],
    icon: '∫', color: '#19b8cc',
  },
  {
    id: 'mar-algebra-mar20',
    courseId: 'algebra',
    title: 'מרתון אלגברה',
    description: 'יום ממוקד לחיזוק כל הנושאים האלגבריים לפני הבגרות.',
    startDateTime: '2026-03-20T09:00',
    duration: 180,
    category: 'bagrut', categoryLabel: 'בגרות',
    level: 'beginner', levelLabel: 'מתחיל',
    totalSpots: 25, spotsLeft: 15,
    topics: ['משוואות', 'פונקציות', 'טריגונומטריה'],
    icon: 'α', color: '#059669',
  },
  {
    id: 'mar-prob-mar20',
    courseId: 'probability',
    title: 'מרתון הסתברות',
    description: 'יום מרוכז לכל חומר ההסתברות לפני הבחינה.',
    startDateTime: '2026-03-20T14:00',
    duration: 180,
    category: 'bagrut', categoryLabel: 'בגרות',
    level: 'intermediate', levelLabel: 'בינוני',
    totalSpots: 30, spotsLeft: 22,
    topics: ['הסתברות', 'משתנים מקריים', 'רגרסיה'],
    icon: 'P', color: '#d97706',
  },
  {
    id: 'mar-calc5-mar20',
    courseId: 'calculus-5',
    title: 'מרתון חשבון 5 יח׳',
    description: 'יום אינטנסיבי מרוכז: פתרון שאלות בגרות, תרגולים ממוקדים ומבחן מדומה מלא.',
    startDateTime: '2026-03-20T11:30',
    duration: 240,
    category: 'bagrut', categoryLabel: 'בגרות',
    level: 'advanced', levelLabel: 'מתקדם',
    totalSpots: 30, spotsLeft: 4,
    topics: ['נגזרות', 'אינטגרלים', 'גבולות', 'תרגולי מבחן'],
    icon: '∫', color: '#19b8cc',
  },
  {
    id: 'mar-calc3-mar20',
    courseId: 'calculus-3',
    title: 'מרתון חשבון 3 יח׳',
    description: 'סיכום וחזרה על כל חומר חשבון 3 יחידות לקראת הבגרות.',
    startDateTime: '2026-03-20T18:00',
    duration: 180,
    category: 'bagrut', categoryLabel: 'בגרות',
    level: 'intermediate', levelLabel: 'בינוני',
    totalSpots: 20, spotsLeft: 12,
    topics: ['נגזרות', 'אינטגרל ראשון', 'פונקציות', 'שאלות בגרות'],
    icon: '∂', color: '#7c3aed',
  },
  {
    id: 'mar-algebra-mar8',
    courseId: 'algebra',
    title: 'מרתון אלגברה',
    description: 'יום ממוקד לחיזוק כל הנושאים האלגבריים לפני הבגרות.',
    startDateTime: '2026-03-08T09:00',
    duration: 180,
    category: 'bagrut', categoryLabel: 'בגרות',
    level: 'beginner', levelLabel: 'מתחיל',
    totalSpots: 25, spotsLeft: 18,
    topics: ['משוואות', 'פונקציות', 'טריגונומטריה'],
    icon: 'α', color: '#059669',
  },
  {
    id: 'mar-prob-mar27',
    courseId: 'probability',
    title: 'מרתון הסתברות',
    description: 'יום מרוכז לכל חומר ההסתברות לפני הבחינה.',
    startDateTime: '2026-03-27T10:00',
    duration: 180,
    category: 'bagrut', categoryLabel: 'בגרות',
    level: 'intermediate', levelLabel: 'בינוני',
    totalSpots: 30, spotsLeft: 24,
    topics: ['הסתברות', 'משתנים מקריים', 'רגרסיה'],
    icon: 'P', color: '#d97706',
  },
  /* ── April–June 2026 ── */
  {
    id: 'calc5-apr-2026',
    courseId: 'calculus-5',
    title: 'מרתון חשבון 5 יח׳',
    description: 'יום אינטנסיבי מרוכז לקראת הבגרות: תרגולים ממוקדים ומבחן מדומה מלא.',
    startDateTime: '2026-04-10T09:00',
    duration: 300,
    category: 'bagrut', categoryLabel: 'בגרות',
    level: 'advanced', levelLabel: 'מתקדם',
    totalSpots: 30, spotsLeft: 7,
    topics: ['נגזרות', 'אינטגרלים', 'גבולות', 'תרגולי מבחן מלאים'],
    icon: '∫', color: '#19b8cc',
  },
  {
    id: 'algebra-may-2026',
    courseId: 'algebra',
    title: 'מרתון אלגברה',
    description: 'יום ממוקד לחיזוק כל הנושאים האלגבריים לפני הבגרות. מתאים לכל הרמות.',
    startDateTime: '2026-05-03T09:00',
    duration: 240,
    category: 'bagrut', categoryLabel: 'בגרות',
    level: 'beginner', levelLabel: 'מתחיל',
    totalSpots: 25, spotsLeft: 15,
    topics: ['משוואות', 'פונקציות', 'טריגונומטריה', 'גיאומטריה'],
    icon: 'α', color: '#059669',
  },
  {
    id: 'calc3-may-2026',
    courseId: 'calculus-3',
    title: 'מרתון חשבון 3 יח׳',
    description: 'יום ספרינט ממוקד לחשבון 3 יחידות — לחזור על הכל ולהיכנס לבחינה בטוחים.',
    startDateTime: '2026-05-18T09:00',
    duration: 240,
    category: 'bagrut', categoryLabel: 'בגרות',
    level: 'intermediate', levelLabel: 'בינוני',
    totalSpots: 20, spotsLeft: 20,
    topics: ['נגזרות', 'אינטגרל ראשון', 'פונקציות', 'שאלות בגרות'],
    icon: '∂', color: '#7c3aed',
  },
  {
    id: 'prob-jun-2026',
    courseId: 'probability',
    title: 'מרתון הסתברות',
    description: 'יום מרוכז לכל חומר ההסתברות — כל מה שצריך לדעת לפני הבחינה.',
    startDateTime: '2026-06-02T09:00',
    duration: 180,
    category: 'bagrut', categoryLabel: 'בגרות',
    level: 'intermediate', levelLabel: 'בינוני',
    totalSpots: 30, spotsLeft: 30,
    topics: ['הסתברות', 'משתנים מקריים', 'רגרסיה', 'תרגול מבחן'],
    icon: 'P', color: '#d97706',
  },
];
